### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by happygirlzt** [FSE2021anonymous/Recoder#11]
Hi there, thank you very much for open-sourcing the work!
I wonder what devices you used for the work. Since I tried to run the training in a machine with 8 Tesla V100-SXM2-16GB, but cannot make it. Besides, I found the code would only utilize 2 GPUs, although I did not specify. I modified the device setting inside `run.py`, but still cannot change the fact that only 2 GPUs are used.
Please kindly suggest. Thank you in advance!
<img width="1261" alt="Screenshot 2022-08-01 at 15 36 30" src="https://user-images.githubusercontent.com/15061984/182097799-12036b18-d48b-4291-ba34-334994c9740c.png">

**Comment by happygirlzt** [comment]
Hi @pkuzqh , I've got another issue when running the code.

<img width="1017" alt="Screenshot 2022-08-02 at 21 41 50" src="https://user-images.githubusercontent.com/15061984/182389229-89f937f2-027f-4719-a3ca-c99954cb15b3.png">

**Comment by pkuzqh** [comment]
If you want to change the batch size, you need to change the number in the dict "args". If you want to use multiple GPUs, you need to modify "model = nn.DataParallel(model, device_ids=[0, 1])".

**Comment by happygirlzt** [comment]
Hi @pkuzqh, thank you for the reply. The `cuda out of memory` issue has been resolved. However, I found the new error above. Please kindly suggest, thanks.

**Comment by pkuzqh** [comment]
How many GPUs do you use? And the batch size?

**Comment by happygirlzt** [comment]
3, I indicated in the `train()` that: `device_ids=[1,2,3]`
the batch size is `16`

**Comment by pkuzqh** [comment]
You need to change the number "4" in line 103-106 to a multiple of 3. And the batch size needs to be a multiple of 3.

**Comment by happygirlzt** [comment]
OK, thank you very much @pkuzqh ! It can now run. However, I saw in the `train()`, the number of epochs is `100000`, `for epoch in range(100000): ` is that true?

**Comment by happygirlzt** [comment]
BTW, for inference, it looks like the `testDefect4j.py` can only use 1 GPU? Since I have 4 GPUs, only one was used, and it caused an OOM issue.
<img width="1305" alt="Screenshot 2022-08-08 at 12 40 19" src="https://user-images.githubusercontent.com/15061984/183340531-76b827d0-1285-456f-a762-e0267ecf7f96.png">

**Comment by pkuzqh** [comment]
you can use "nn.DataParallel" to use multiple gpus in testDefect4J.py
