### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by mlyzy** [FSE2021anonymous/Recoder#14]
when I run the python file, there is a error
I think this error about the sentence "loss, _ = model(dBatch[0], dBatch[1], dBatch[2], dBatch[3], dBatch[4], dBatch[6], dBatch[7], dBatch[8], dBatch[9], tmpf, tmpc, tmpindex, tmpchar, tmpindex2, rulead, antimask2, dBatch[5])"
Can you help me with this questions：

Traceback (most recent call last):
  File "run.py", line 1208, in <module>
    train()
  File "run.py", line 189, in train
    loss, _ = model(dBatch[0], dBatch[1], dBatch[2], dBatch[3], dBatch[4], dBatch[6], dBatch[7], dBatch[8], dBatch[9], tmpf, tmpc, tmpindex, tmpchar, tmpindex2, rulead, antimask2, dBatch[5])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/Repair/Model.py", line 128, in forward
    charEm = self.conv(charEm.permute(0, 3, 1, 2))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

**Comment by pkuzqh** [comment]
Maybe "cuda out of memory"

**Comment by QingyuanLi1211** [comment]
请问您解决了这个问题吗？我在使用CUDA_VISIBLE_DEVICES=0 python3 testDefect4j1.py Chart-1时同样出现了以上报错，在更换到空闲的1卡之后仍然不起作用，怀疑不是cuda oom导致的。

**Comment by guoweijun137** [comment]
@HanJin996 @pkuzqh   When I run "CUDA_VISIBLE_DEVICES=0 python3 testDefect4j.py Chart-1", Terminal tell me "RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR".Y Have you solved this issue? Can you help me solve this problem:
root@dfc61105838c:~/Repair# CUDA_VISIBLE_DEVICES=0 python3 testDefect4j.py Chart-1
else_statement -> BlockStatement
using GPU
p
Checking out 2266 to /root/Repair/buggy.................................... OK
Init local repository...................................................... OK
Tag post-fix revision...................................................... OK
Apply patch................................................................ OK
Run post-checkout hook..................................................... OK
Excluding broken/flaky tests............................................... OK
Excluding broken/flaky tests............................................... OK
Initialize fixed program version........................................... OK
Apply patch................................................................ OK
Initialize buggy program version........................................... OK
Diff 2266:2264............................................................. OK
Apply patch................................................................ OK
Tag pre-fix revision....................................................... OK
Check out program version: Chart-1b........................................ OK
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=1G; support was removed in 8.0
Running ant (export.dir.src.classes)....................................... OK

path org.jfree.chart.renderer.category.AbstractCategoryItemRenderer
path org.jfree.chart.renderer.category.AbstractCategoryItemRenderer
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.plot.CategoryPlot
path org.jfree.chart.renderer.category.LineAndShapeRenderer
path org.jfree.chart.renderer.category.LineAndShapeRenderer
path org.jfree.chart.renderer.category.AbstractCategoryItemRenderer
path org.jfree.chart.renderer.category.AbstractCategoryItemRenderer
path org.jfree.chart.renderer.category.AbstractCategoryItemRenderer
path org.jfree.chart.renderer.category.AbstractCategoryItemRenderer
path org.jfree.chart.renderer.category.AbstractCategoryItemRenderer
path org.jfree.chart.renderer.category.AbstractCategoryItemRenderer
path org.jfree.chart.plot.CategoryPlot
path org.jfree.data.category.DefaultCategoryDataset
path org.jfree.data.category.DefaultCategoryDataset
  0%|                                                     | 0/2 [01:22<?, ?it/s]
Traceback (most recent call last):
  File "testDefect4j.py", line 645, in <module>
    solveone(data, model)
  File "/root/Repair/run.py", line 1078, in solveone
    ans = BeamSearch((x[0], x[1], None, None, None, None, None, None, x[2], x[3]), dev_set, model, 150, args.batch_size, indexs)
  File "/root/Repair/run.py", line 538, in BeamSearch
    result = model(gVar(tmpnl), gVar(tmpnlad), gVar(tmprule), gVar(tmpruleparent), gVar(tmprulechild), gVar(tmpAd), gVar(tmptreepath), gVar(tmpnl8), gVar(tmpnl9), tmpf, tmpc, tmpindex, tmpchar, tmpindex2, rulead, antimasks, None, "test")
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/Repair/Model.py", line 128, in forward
    charEm = self.conv(charEm.permute(0, 3, 1, 2))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
